In [106]:
#import the modules
import numpy as np
import pandas as pd

In [107]:
#Reading the data
data=pd.read_csv("LoanApprovalPrediction.csv")

In [108]:
#checking the first 10 rows of the dataset
data.head()

Loan_ID Gender Married  Dependents     Education Self_Employed  \
0  LP001002   Male      No         0.0      Graduate            No   
1  LP001003   Male     Yes         1.0      Graduate            No   
2  LP001005   Male     Yes         0.0      Graduate           Yes   
3  LP001006   Male     Yes         0.0  Not Graduate            No   
4  LP001008   Male      No         0.0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [109]:
#basic analysis
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 598 entries, 0 to 597
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            598 non-null    object 
 1   Gender             598 non-null    object 
 2   Married            598 non-null    object 
 3   Dependents         586 non-null    float64
 4   Education          598 non-null    object 
 5   Self_Employed      598 non-null    object 
 6   ApplicantIncome    598 non-null    int64  
 7   CoapplicantIncome  598 non-null    float64
 8   LoanAmount         577 non-null    float64
 9   Loan_Amount_Term   584 non-null    float64
 10  Credit_History     549 non-null    float64
 11  Property_Area      598 non-null    object 
 12  Loan_Status        598 non-null    object 
dtypes: float64(5), int64(1), object(7)
memory usage: 60.9+ KB


In [110]:
#checking the null value and categorical value
data.isna().sum()

Loan_ID               0
Gender                0
Married               0
Dependents           12
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           21
Loan_Amount_Term     14
Credit_History       49
Property_Area         0
Loan_Status           0
dtype: int64

In [111]:
#converting categorical value to numerical representations
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()

In [112]:
data['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [113]:
data['Gender']=label_encoder.fit_transform(data['Gender'])

In [114]:
data['Gender'].unique()

array([1, 0])

In [115]:
data['Married'].unique()

array(['No', 'Yes'], dtype=object)

In [116]:
data['Married']=label_encoder.fit_transform(data['Married'])

In [117]:
data['Married'].unique()

array([0, 1])

In [118]:
data.head()

Loan_ID  Gender  Married  Dependents     Education Self_Employed  \
0  LP001002       1        0         0.0      Graduate            No   
1  LP001003       1        1         1.0      Graduate            No   
2  LP001005       1        1         0.0      Graduate           Yes   
3  LP001006       1        1         0.0  Not Graduate            No   
4  LP001008       1        0         0.0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [119]:
data['Education'].unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [120]:
data['Education']=label_encoder.fit_transform(data['Education'])

In [121]:
data['Education'].unique()

array([0, 1])

In [122]:
data['Self_Employed'].unique()

array(['No', 'Yes'], dtype=object)

In [123]:
data['Self_Employed']=label_encoder.fit_transform(data['Self_Employed'])

In [124]:
data['Self_Employed'].unique()

array([0, 1])

In [125]:
data['Property_Area'].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [126]:
data['Property_Area']=label_encoder.fit_transform(data['Property_Area'])

In [127]:
data['Property_Area'].unique()

array([2, 0, 1])

In [128]:
data['Loan_Status'].unique()

array(['Y', 'N'], dtype=object)

In [129]:
data['Loan_Status']=label_encoder.fit_transform(data['Loan_Status'])

In [130]:
data['Loan_Status'].unique()

array([1, 0])

In [131]:
data.head()

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0  LP001002       1        0         0.0          0              0   
1  LP001003       1        1         1.0          0              0   
2  LP001005       1        1         0.0          0              1   
3  LP001006       1        1         0.0          1              0   
4  LP001008       1        0         0.0          0              0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History  Property_Area  Loan_Status  
0             1.0              2            1  
1             1.0              0            0  
2             1.0              2            1  
3             1.0              2            1  
4             1.0              2            1

In [132]:
df=data.drop(['Loan_ID'],axis=1)

In [133]:
df.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0         0.0          0              0             5849   
1       1        1         1.0          0              0             4583   
2       1        1         0.0          0              1             3000   
3       1        1         0.0          1              0             2583   
4       1        0         0.0          0              0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0         NaN             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

   Property_Area  Loan_Status  
0              2            1  
1              0            0  
2              2            1  
3              2            1  
4              2            1

In [134]:
df.isna().sum()

Gender                0
Married               0
Dependents           12
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           21
Loan_Amount_Term     14
Credit_History       49
Property_Area         0
Loan_Status           0
dtype: int64

In [135]:
#Removing the null value
for col in df.columns:
    df[col]=df[col].fillna(df[col].mean())

In [136]:
df.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0         0.0          0              0             5849   
1       1        1         1.0          0              0             4583   
2       1        1         0.0          0              1             3000   
3       1        1         0.0          1              0             2583   
4       1        0         0.0          0              0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0  144.968804             360.0             1.0   
1             1508.0  128.000000             360.0             1.0   
2                0.0   66.000000             360.0             1.0   
3             2358.0  120.000000             360.0             1.0   
4                0.0  141.000000             360.0             1.0   

   Property_Area  Loan_Status  
0              2            1  
1              0            0  
2              2            1  
3              2            1  
4              2            1

In [137]:
#dividing the data into independent and dependent variables
x=df.drop(['Loan_Status'],axis=1)
y=df['Loan_Status']

In [138]:
x.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0         0.0          0              0             5849   
1       1        1         1.0          0              0             4583   
2       1        1         0.0          0              1             3000   
3       1        1         0.0          1              0             2583   
4       1        0         0.0          0              0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0  144.968804             360.0             1.0   
1             1508.0  128.000000             360.0             1.0   
2                0.0   66.000000             360.0             1.0   
3             2358.0  120.000000             360.0             1.0   
4                0.0  141.000000             360.0             1.0   

   Property_Area  
0              2  
1              0  
2              2  
3              2  
4              2

In [139]:
#Splitting the data into train and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.80)

In [142]:
##creating a supervised ML using Linear Regression model
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [144]:
model.fit(x_train,y_train)  #training the model

C:\Users\Dell\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [148]:
#Predictions usi
y_hat=model.predict(x_test)   

In [150]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_hat)

In [152]:
print(score)

0.8166666666666667
